### ISSUE TITLE
hub.sls broken

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/builder-base-formula#58]
@giorgiosironi , I'm getting this attempting to build elife-libraries on vagrant:

```
==> elife-libraries--vagrant: [CRITICAL] Rendering SLS 'base:elife.hub' failed: Jinja variable 'dict object' has no attribute 'home'
==> elife-libraries--vagrant: local:
==> elife-libraries--vagrant:     Data failed to compile:
==> elife-libraries--vagrant: ----------
==> elife-libraries--vagrant:     Rendering SLS 'base:elife.hub' failed: Jinja variable 'dict object' has no attribute 'home'
```
caused by a line in `elife/hub.sls` that looks like:
```
    file.managed:
        - name: {{ salt['user.info'](pillar.elife.hub.username).home }}/.config/hub
```
I'm not sure what it's supposed to be doing so I'm not going to attempt to 'fix' it.

**Comment by giorgiosironi** [comment]
This is attempting to find out the home directory of the user that should use the `hub` cli tool to interact with Github (https://github.com/github/hub). Sometimes this is `/home/elife`, sometimes it is `/var/lib/jenkins`.

I think that this runs at Jinja compile time, and that the directory doesn't exist on a new machine. We should switch it to a case-by-case definition (if `elife`, if `jenkins`...) or perhaps work around it with something like `su {{ pillar.elife.hub.username}} sh -c 'cd; echo ... > ./config/hub`?

**Comment by lsh-0** [comment]
I thought it might be something like that but I couldn't find the docs on `user.info` to verify. There is `user.present`: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present

and there is also this neat trick: `eval echo "~$username"`:  https://stackoverflow.com/questions/20504662/how-to-get-home-directory-of-different-user-in-bash-script

**Comment by giorgiosironi** [comment]
See attached PR
